export const BRANCHES = [
  { id: "what", name: "知识是什么", hint: "什么算是知道", x: -14, color: "#e0b56a" },
  { id: "source", name: "知识从哪里来", hint: "理性，还是经验", x: -7, color: "#7eb6c9" },
  { id: "experience", name: "经验何以成为知识", hint: "经验怎样被组织", x: 0, color: "#d4846a" },
  { id: "world", name: "外部世界如何建立", hint: "对象怎样被构造", x: 7, color: "#f0d78c" },
  { id: "structure", name: "知识体系的结构", hint: "地基，还是网络", x: 14, color: "#8fb59a" },
];

export const KIND = {
  develop: { color: "#c5ccd1", name: "推进" },
  answer: { color: "#e6d3a1", name: "回应" },
  contrast: { color: "#8ea6b8", name: "对峙" },
  fork: { color: "#c989a4", name: "分叉" },
  critique: { color: "#e07a64", name: "批判" },
  lineage: { color: "#d2b072", name: "延续" },
};

const TIER = { core: "必读主干", supplement: "补历史或分叉", contemporary: "当代转向" };

export function tierName(tier) {
  return TIER[tier];
}

export const NODES = [
  {
    id: "plato",
    thinker: "柏拉图",
    work: "《泰阿泰德篇》",
    original: "Theaetetus",
    year: -369,
    yearLabel: "约前 369",
    branch: "what",
    tier: "core",
    z: -0.4,
    claim: "知识是什么？",
    move: "对话检验了“得到辩护的真信念”这一路说法，没有留下一个被公认的最终定义。问题本身从此站住。",
    place: "“知识是什么”这条问题的源头。",
  },
  {
    id: "descartes",
    thinker: "笛卡尔",
    work: "《第一哲学沉思集》",
    original: "Meditationes de prima philosophia",
    year: 1641,
    yearLabel: "1641",
    branch: "source",
    tier: "core",
    z: -0.5,
    claim: "什么东西是绝对确定的？",
    move: "方法怀疑之后，剩下“我思”。确定性被放在理性一边，近代认识论从这里开始。",
    place: "理性主义的起点。最短阅读链从洛克算起，这一本仍是必读主干。",
  },
  {
    id: "locke",
    thinker: "洛克",
    work: "《人类理解论》",
    original: "An Essay Concerning Human Understanding",
    year: 1689,
    yearLabel: "1689",
    branch: "source",
    tier: "supplement",
    spine: true,
    z: 0.3,
    claim: "知识是否来自经验？",
    move: "心灵如白板，观念来自经验。知识是对观念之间契合或背离的知觉。他区分第一性质与第二性质。",
    place: "经验论体系。理解《世界的逻辑构造》时，最短阅读链从这里进入。",
  },
  {
    id: "berkeley",
    thinker: "贝克莱",
    work: "《人类知识原理》",
    original: "A Treatise Concerning the Principles of Human Knowledge",
    year: 1710,
    yearLabel: "1710",
    branch: "source",
    tier: "supplement",
    z: 1.5,
    claim: "如果知识来自经验，物质实体还有必要吗？",
    move: "存在即被感知。对象是观念的集合，一个独立于心灵的物质基底并不被经验要求。",
    place: "经验论被推向观念论。阅读链可以经过他，也可以从洛克直接到休谟。",
  },
  {
    id: "hume",
    thinker: "休谟",
    work: "《人类理解研究》",
    original: "An Enquiry Concerning Human Understanding",
    year: 1748,
    yearLabel: "1748",
    branch: "source",
    tier: "core",
    spine: true,
    z: -1.8,
    claim: "经验究竟能证明多少？",
    move: "经验里只有先后相续，没有因果的必然联结。归纳不能由经验证明。自我也不是一个被给予的实体。",
    place: "近代认识论最硬的一击。纵深上他靠后，表示这是一个挑战，等着被回应。",
  },
  {
    id: "kant",
    thinker: "康德",
    work: "《纯粹理性批判》",
    original: "Kritik der reinen Vernunft",
    year: 1781,
    yearLabel: "1781",
    branch: "experience",
    tier: "core",
    spine: true,
    z: 0,
    claim: "经验何以可能？",
    move: "主体带着时空形式和范畴组织感觉，经验才成为知识。我们认识现象。物自身不进入理论知识。",
    place: "对经验论和理性主义的综合。后面分成两条路：马赫的科学经验主义，胡塞尔的现象学。",
  },
  {
    id: "mach",
    thinker: "马赫",
    work: "《感觉的分析》",
    original: "Beiträge zur Analyse der Empfindungen",
    year: 1886,
    yearLabel: "1886",
    branch: "experience",
    tier: "supplement",
    spine: true,
    z: 0.7,
    claim: "能否只从感觉要素出发，不预设实体？",
    move: "物体和自我都被分析成感觉要素及其函数关系。要素是描述的起点。",
    place: "卡尔纳普的重要前史。初版在 1886 年，后来以《感觉的分析》之名再版。",
  },
  {
    id: "husserl",
    thinker: "胡塞尔",
    work: "《逻辑研究》《观念 I》",
    original: "Logische Untersuchungen, 1900–01；Ideen I, 1913",
    year: 1900,
    yearLabel: "1900",
    branch: "experience",
    tier: "supplement",
    z: -2.7,
    claim: "意识的结构本身能否被描述？",
    move: "逻辑不能化成心理联想。意识总是关于某物的意识。现象学用还原去描述经验如何呈现对象。",
    place: "从康德分出的另一支，落在纵深的后方，和马赫那条科学经验主义路线分开。",
  },
  {
    id: "russell-problems",
    thinker: "罗素",
    work: "《哲学问题》",
    original: "The Problems of Philosophy",
    year: 1912,
    yearLabel: "1912",
    branch: "world",
    tier: "core",
    z: -1.3,
    claim: "感觉材料与外部世界的知识是什么关系？",
    move: "区分亲知与摹状。外部世界不能被简单地当成当前感觉，需要说明我们凭什么相信它。",
    place: "分析哲学的入口，放在必读主干。和《构造》贴得更近的是次年的逻辑构造方案。",
  },
  {
    id: "russell-external",
    thinker: "罗素",
    work: "《我们关于外部世界的知识》",
    original: "Our Knowledge of the External World",
    year: 1914,
    yearLabel: "1914",
    branch: "world",
    tier: "supplement",
    spine: true,
    z: 0.35,
    claim: "物理对象能否是感觉材料的逻辑构造？",
    move: "与其推论出一个看不见的物质实体，不如把物理对象定义为感觉材料之间的逻辑构造。",
    place: "和《世界的逻辑构造》关系最直接的一本。",
  },
  {
    id: "carnap-aufbau",
    thinker: "卡尔纳普",
    work: "《世界的逻辑构造》",
    original: "Der logische Aufbau der Welt",
    year: 1928,
    yearLabel: "1928",
    branch: "world",
    tier: "core",
    spine: true,
    hero: true,
    z: 0.45,
    claim: "能否从最基础的经验出发，用逻辑关系逐层构造出整个概念世界？",
    move: "起点是经验之间的相似关系。感觉性质、物理对象、他人的身体与心理、社会文化对象，直到科学世界，都由显式定义逐层搭出来。",
    place: "在传统分类里，它主要是认识论问题，用逻辑方法来做。在问题网络里，它是“认识”通向“表征”的桥：感觉是起点，逻辑是工具，构造系统是模型。",
    bridge: "书名像在讲世界由什么构成。它处理的是：我们称为世界的那套概念，怎样从基本经验被重建出来。",
  },
  {
    id: "carnap-syntax",
    thinker: "卡尔纳普",
    work: "《哲学与逻辑句法》",
    original: "Philosophy and Logical Syntax, 1935",
    year: 1935,
    yearLabel: "1935",
    branch: "structure",
    tier: "supplement",
    z: -0.6,
    claim: "哲学问题能否改写成语言的形式问题？",
    move: "关注点从构造世界转到构造语言。许多哲学争论被要求先说清自己使用的语言框架。",
    place: "1935 年的讲演小册。同一转向的完整表述是 1934 年《语言的逻辑句法》。",
  },
  {
    id: "quine",
    thinker: "奎因",
    work: "《经验主义的两个教条》",
    original: "Two Dogmas of Empiricism",
    year: 1951,
    yearLabel: "1951",
    branch: "structure",
    tier: "core",
    spine: true,
    z: 1.7,
    claim: "陈述能否被逐条还原成经验？",
    move: "分析与综合的二分，以及每个陈述单独接受经验检验的还原主义，都被他拆掉。面对经验的是整张知识之网。",
    place: "对《构造》的第一路批判：还原到基础经验这条路走不通。纵深上靠前，表示转折已经来到台前。",
  },
  {
    id: "sellars",
    thinker: "塞拉斯",
    work: "《经验主义与心灵哲学》",
    original: "Empiricism and the Philosophy of Mind",
    year: 1956,
    yearLabel: "1956",
    branch: "experience",
    tier: "core",
    spine: true,
    z: 1.9,
    claim: "有没有未经概念化的纯经验，可以当知识的地基？",
    move: "所予神话：感觉并不是一块还没进入概念、却又能充当证据的纯粹材料。观察本身已经在概念空间里。",
    place: "对《构造》的第二路批判，打在“经验”这一列，而不是“体系结构”那一列。阅读顺序上常排在奎因之后，论证上与奎因并列。",
  },
  {
    id: "gettier",
    thinker: "盖梯尔",
    work: "《有辩护的真信念是知识吗？》",
    original: "Is Justified True Belief Knowledge?",
    year: 1963,
    yearLabel: "1963",
    branch: "what",
    tier: "contemporary",
    z: -1.5,
    claim: "得到辩护的真信念就够称为知识吗？",
    move: "两个反例表明：信念为真，辩护也在，仍可能只是碰巧。1963 年以后，“知识是什么”重新成为独立问题。",
    place: "当代认识论的分水岭。纵深靠后，它是一个反例，不是一套新体系。",
  },
  {
    id: "goldman",
    thinker: "戈德曼",
    work: "《一种因果的知识理论》",
    original: "A Causal Theory of Knowing",
    year: 1967,
    yearLabel: "1967",
    branch: "what",
    tier: "contemporary",
    z: 1.7,
    claim: "知识是否取决于与事实之间的可靠联系？",
    move: "知道一件事，要求信念和使它为真的事实之间有恰当的因果关联。可靠主义从这一路长出来。",
    place: "外在主义。辩护不再只是主体内心里的理由。",
  },
  {
    id: "nozick",
    thinker: "诺齐克",
    work: "《哲学解释》",
    original: "Philosophical Explanations",
    year: 1981,
    yearLabel: "1981",
    branch: "what",
    tier: "contemporary",
    z: 2.5,
    claim: "知识是否需要追踪真理？",
    move: "若命题为假，你不会相信它；若命题为真，你会相信它。知识是对真理的追踪，而不是一份内部证书。",
    place: "追踪理论。和戈德曼一样，把知识的条件放到主体之外的反事实关系上。",
  },
  {
    id: "williamson",
    thinker: "威廉姆森",
    work: "《知识及其限度》",
    original: "Knowledge and Its Limits",
    year: 2000,
    yearLabel: "2000",
    branch: "what",
    tier: "contemporary",
    z: 0.4,
    claim: "知识是否应当被当成基础概念？",
    move: "知识是一种基本心理状态，不必再拆成信念、真理和辩护。证据与断言的界限由知识来划。",
    place: "knowledge-first。当代这一列从柏拉图的问题出发，到这里变成一种新的起点。",
  },
];

export const EDGES = [
  { from: "plato", to: "gettier", kind: "lineage", bend: 1, via: "“有辩护的真信念”重新被拿来检验" },
  { from: "gettier", to: "goldman", kind: "lineage", bend: 1, via: "反例之后，知识被改写为与事实的因果联系" },
  { from: "gettier", to: "nozick", kind: "lineage", bend: -1, via: "反例之后，知识被改写为对真理的追踪" },
  { from: "gettier", to: "williamson", kind: "lineage", bend: 1, via: "知识不再被还原为信念加真理加辩护" },
  { from: "descartes", to: "locke", kind: "contrast", bend: 1, via: "理性中的确定性，对上经验中的观念" },
  { from: "locke", to: "berkeley", kind: "develop", bend: -1, via: "经验论被推到：物质实体是否多余" },
  { from: "berkeley", to: "hume", kind: "develop", bend: -1, via: "继续追问因果、归纳和自我" },
  { from: "locke", to: "hume", kind: "develop", spine: true, bend: 1, via: "经验论走到自己的边界" },
  { from: "hume", to: "kant", kind: "answer", spine: true, bend: 1, via: "用先验结构回答因果与经验何以可能" },
  { from: "kant", to: "mach", kind: "develop", spine: true, bend: 1, via: "退回感觉要素，不再预设实体" },
  { from: "kant", to: "husserl", kind: "fork", bend: -1, via: "现象学另起，描述意识的意向结构" },
  { from: "mach", to: "russell-external", kind: "develop", spine: true, bend: 1, via: "从感觉要素走到对象的逻辑构造" },
  { from: "russell-problems", to: "russell-external", kind: "develop", bend: -1, via: "从感觉材料问题走到逻辑构造方案" },
  { from: "russell-external", to: "carnap-aufbau", kind: "develop", spine: true, bend: 1, via: "把逻辑构造做成覆盖全部概念的系统" },
  { from: "carnap-aufbau", to: "carnap-syntax", kind: "develop", bend: 1, via: "从构造世界转向构造语言" },
  { from: "carnap-aufbau", to: "quine", kind: "critique", spine: true, bend: 1, via: "陈述不能逐条还原到经验，知识是一张网" },
  { from: "carnap-aufbau", to: "sellars", kind: "critique", spine: true, bend: -1, via: "纯经验地基本身是所予神话" },
];

export const SPINE = ["locke", "hume", "kant", "mach", "russell-external", "carnap-aufbau", "quine", "sellars"];

export const LADDER = [
  { id: "L1", name: "我的瞬时经验", text: "构造的起点。先不假定物质实体，只从主体当下的经验出发。" },
  { id: "L2", name: "相似关系", text: "用来建造上层的基本关系，是经验与经验之间的相似性。" },
  { id: "L3", name: "感觉性质", text: "颜色、声音这类性质，由相似关系定义出来。" },
  { id: "L4", name: "物理对象", text: "日常物体是这些关系的逻辑复合，而不是藏在经验背后的实体。" },
  { id: "L5", name: "空间中的对象", text: "对象被放进空间秩序，世界开始有位置和广延。" },
  { id: "L6", name: "他人的身体", text: "其他人类身体也要能从这套构造里定义出来。" },
  { id: "L7", name: "他人的心理", text: "他人的心灵不是直接给予的，是在身体和表达之上被构造的。" },
  { id: "L8", name: "社会文化对象", text: "制度、作品、共同体这些主体间的对象继续往上生成。" },
  { id: "L9", name: "科学世界", text: "科学概念处在构造链的上层，和日常世界是同一套系统。" },
];

export function layoutY(year) {
  if (year < 1500) return -5.6;
  if (year <= 1781) return ((year - 1641) / (1781 - 1641)) * 7.4;
  if (year <= 1886) return 7.4 + ((year - 1781) / (1886 - 1781)) * 2.1;
  return 9.5 + ((year - 1886) / (2000 - 1886)) * 12.2;
}

export const YEAR_MARKS = [
  { year: -369, label: "约前 369" },
  { year: 1641, label: "1641" },
  { year: 1748, label: "1748" },
  { year: 1781, label: "1781" },
  { year: 1886, label: "1886" },
  { year: 1928, label: "1928" },
  { year: 1951, label: "1951" },
  { year: 1963, label: "1963" },
  { year: 2000, label: "2000" },
];
